### ISSUE TITLE
ID?

### ISSUE THREAD

**Issue by LopeKinz** [Jakee8718/fast-github-view-bot#1]
Where can i get the ID or Key needed to increase views?

**Comment by Jakee8718** [comment]
thank you for making an issue. On your profile click on the profile views and in the URL you can find the id. I'll help you though and just give you your id. here: **0d1de15e24948dd99abb01df1eb7a3aca4bb15e19e44670b8d0cb837e12f38a1/68747470733a2f2f6b6f6d617265762e636f6d2f67687076632f3f757365726e616d653d6c6f70656b696e7a266c6162656c3d50726f66696c65253230766965777326636f6c6f723d306537356236267374796c653d666c6174**
